### ISSUE TITLE
Data Preprocessing Pipeline

### ISSUE THREAD

**Issue by mozharovsky** [formermagic/formerbox#10]
## Tasks
- [x] Multithreaded source code pre-tokenization
- [x] BPE Tokenizer training
- [x] Modular tokenized datasets binarization
- [x] Common API to convert input jsonl data files into a tuple of (tokenizer + indexed dataset)
