### ISSUE TITLE
BART seq2seq pre-training for sentence classification and NMT

### ISSUE THREAD

**Issue by mozharovsky** [formermagic/formerbox#7]
## Overview

Our current approach is based on RoBERTa model pretrained on our Python/AST code dataset which is not enough for NLG tasks such as neural machine translation or summarization. The future product should have a way to translate code changes into a short description in natural language. This feature has a seq2seq nature which means the need of such models in our research toolkit. 

mBART ([Multilingual Denoising Pre-training for Neural Machine Translation, 2001.08210](https://arxiv.org/pdf/2001.08210.pdf)) looks promising. This model is available via **🤗/Transformers** library and can be modified for an NMT pipeline with **PyTorchLightning**. 

## Roadmap

- [x] Prepare the pretraining tools & data
- [x] Wrap <s>mBART</s> BART around a seq2seq pipeline
- [x] Setup metrics for seq2seq models
- [x] Pretrain a model for sentence-classification task
- [ ] <s>Prepare / fine-tune a model for an NMT task</s>

**Comment by mozharovsky** [comment]
Quick update: we pretrained a BART model on python 1M dataset. 

We still believe in NMT pipelines for generative tasks and yet it's a subject of further research. For now we're fine with denoising pretraining (BART, T5, etc) for learning programming lang essential features for document classification task. Additionally, we'll be able to use same techniques for fine-tuning on a generative downstream task.
